force-app/main/default/objects/integration__c/integration__c.object-meta.xml
<CustomObject>
    <label>integration</label>
    <nameField>
        <label>integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>integration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/integration__c/fields/ipField__c.field-meta.xml
<CustomField>
    <fullName>ipField__c</fullName>
    <label>ipField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationSchedule.cls
public class IntegrationSchedule implements Schedulable {
    // Scheduler lets you delay execution so that you can run Apex classes at a specified time. 
    public static void execute(SchedulableContext context) {
       System.debug('Schedulable Context here:' + context);

        List<integration__c> dataIpList = [SELECT ipField__c, Id FROM integration__c];
        for (integration__c objRec : dataIpList){
            //check data quality
            if ((objRec.ipField__c != null) & (objRec.Id != null)){
                System.enqueueJob(new IntegrationCalloutQueueable(objRec.ipField__c, objRec.Id));
            } else {
                System.debug ('Wrong data from query, check records');
            }
        }
    }
    // call this in Anonymous apex to schedule job 
    // IntegrationSchedule  schClass = new IntegrationSchedule(); 
    // String cronExp = '0 11 * * * ?';
    // System.schedule('IntegrationWork', cronExp, schClass);
}