force-app/main/default/objects/integration__c/integration__c.object-meta.xml
<CustomObject>
    <label>integration</label>
    <nameField>
        <label>integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>integration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/integration__c/fields/cityField__c.field-meta.xml
<CustomField>
    <fullName>cityField__c</fullName>
    <label>cityField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/countryField__c.field-meta.xml
<CustomField>
    <fullName>countryField__c</fullName>
    <label>countryField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/dateTimeField__c.field-meta.xml
<CustomField>
    <fullName>dateTimeField__c</fullName>
    <label>dateTimeField</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/ipField__c.field-meta.xml
<CustomField>
    <fullName>ipField__c</fullName>
    <label>ipField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/regionField__c.field-meta.xml
<CustomField>
    <fullName>regionField__c</fullName>
    <label>regionField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationPostmanGet.cls
@RestResource(urlMapping='/territoryInfo/*')
global  class IntegrationPostmanGet{

    global class territoryInfo{
        String city {get;set;}
        String region {get;set;}
        String country {get;set;}
        Datetime dateTimeCustom {get;set;}
    }

    @httpGet
    global static territoryInfo getInfo() {
        RestRequest request = RestContext.Request;
        String somethingId = request.requestURI.substring(request.RequestURI.lastIndexOf('/')+1);
        
        integration__c record = [SELECT id, ipField__c, cityField__c, regionField__c, countryField__c, dateTimeField__c 
        FROM integration__c WHERE id =: somethingId];
        territoryInfo terInfo =  new territoryInfo ();
        terInfo.city = record.cityField__c;
        terInfo.region = record.regionField__c;
        terInfo.country = record.countryField__c;
        terInfo.dateTimeCustom = record.dateTimeField__c;
        return terInfo;
    }
}