force-app/main/default/objects/integration__c/integration__c.object-meta.xml
<CustomObject>
    <label>integration</label>
    <nameField>
        <label>integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>integration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/integration__c/fields/cityField__c.field-meta.xml
<CustomField>
    <fullName>cityField__c</fullName>
    <label>cityField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/countryField__c.field-meta.xml
<CustomField>
    <fullName>countryField__c</fullName>
    <label>countryField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/ipField__c.field-meta.xml
<CustomField>
    <fullName>ipField__c</fullName>
    <label>ipField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/regionField__c.field-meta.xml
<CustomField>
    <fullName>regionField__c</fullName>
    <label>regionField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/tokenCS__c/tokenCS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>tokenCS</label>
</CustomObject>

force-app/main/default/objects/tokenCS__c/fields/tokenData__c.field-meta.xml
<CustomField>
    <fullName>tokenData__c</fullName>
    <label>tokenData</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationPostmanPostWithIPInfo.cls
@RestResource(urlMapping='/apiPostNew/*')
global with sharing class IntegrationPostmanPostWithIPInfo {
    
    @HttpPost
    global static String postInfo (String postName, String postIp){
        tokenCS__c mc = tokenCS__c.getValues('adminToken');
        String token = mc.tokenData__c;
        System.debug('token: ' + token);
        String endPointIp = 'https://ipinfo.io/'+ postIp +'/geo' + token;

        integration__c newRecord = new integration__c();
        newRecord.name = postName;
        newRecord.ipField__c = postIp;

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setMethod('GET');
        request.setEndpoint(endPointIp);
        HttpResponse response = http.send(request);

        if(response.getStatusCode() == 200) {
            Map<String,Object> mapResult = (Map<String,Object>) JSON.deserializeUntyped(response.getBody());
            newRecord.cityField__c = (String) mapResult.get('city');
            newRecord.regionField__c =(String) mapResult.get('region');
            newRecord.countryField__c = (String) mapResult.get('country');
            insert newRecord;
            return ('New record was succusfully created: ' + newRecord.id);
        } else {
            return ('Something wrong with request status. Its not 200');
        }
    }
}