force-app/main/default/objects/integration__c/integration__c.object-meta.xml
<CustomObject>
    <label>integration</label>
    <nameField>
        <label>integration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>integration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/integration__c/fields/cityField__c.field-meta.xml
<CustomField>
    <fullName>cityField__c</fullName>
    <label>cityField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/countryField__c.field-meta.xml
<CustomField>
    <fullName>countryField__c</fullName>
    <label>countryField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/ipField__c.field-meta.xml
<CustomField>
    <fullName>ipField__c</fullName>
    <label>ipField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/integration__c/fields/regionField__c.field-meta.xml
<CustomField>
    <fullName>regionField__c</fullName>
    <label>regionField</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationPostmanPost.cls
@RestResource(urlMapping='/apiPost/*')
global with sharing class IntegrationPostmanPost {
    
    @HttpPost
    global static String postInfo (String postName, String postIp, string postCity, string postRegion, string postCountry){
        integration__c newRecord = new integration__c();
        newRecord.name = postName;
        newRecord.ipField__c = postIp;
        newRecord.cityField__c = postCity;
        newRecord.regionField__c = postRegion;
        newRecord.countryField__c = postCountry;
        insert newRecord;
        return ('New record was succusfully created: ' + newRecord.id);

    }
}